# Generated by Django 5.1 on 2024-08-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='media_link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
